application:
  name: go-gin-server
server:
  http:
    address: localhost
    port: 8080
log:
  level: DEBUG
  format: text
backend:
  dbname: "mongo"
  uri: "mongodb://localhost:27017/?connect=direct"
